import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://meet.hub.niftyai.net/signin');
  await page.getByRole('textbox', { name: 'Enter username' }).click();
  await page.getByRole('textbox', { name: 'Enter username' }).fill('admin');
  await page.getByRole('textbox', { name: 'Enter password' }).click();
  await page.getByRole('textbox', { name: 'Enter password' }).fill('0000');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Tasks' }).click();
  await page.getByRole('link', { name: 'Tasks' }).click();
  await page.getByRole('link', { name: 'History' }).click();
  await page.getByRole('link', { name: 'Tasks' }).click();
  await page.getByRole('link', { name: 'Knowledge Base' }).click();
  await page.getByRole('link', { name: 'Settings' }).click();
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click();
  await page.getByText('Upload Transcript File').click();
  await page.getByText('Drag and drop a transcript').click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('Upload file first').first().click();
  await page.getByText('Choose Project').click();
  await page.getByText('Choose Destination', { exact: true }).click();
  await page.getByText('Uploaded', { exact: true }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('link', { name: 'Tasks' }).click();
  await page.locator('.anticon.anticon-right > svg').first().click();
  await page.getByRole('link', { name: 'History' }).click();
  await page.getByText('completed').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('processing').first().click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Refresh' }).click();
  await page.getByRole('link', { name: 'Knowledge Base' }).click();
  await page.getByText('Drag and drop a file hereor').click();
  await page.getByRole('textbox', { name: 'Search documents...' }).click();
  await page.locator('.anticon.anticon-down > svg').click();
  await page.getByText('Denowatts').nth(3).click();
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click();
  await page.locator('span').filter({ hasText: 'meeting_saved_closed_caption.' }).first().click();
  await page.locator('span').filter({ hasText: 'meeting_saved_closed_caption.' }).first().click();
  await page.getByRole('listitem').filter({ hasText: 'meeting_saved_closed_caption.txt41.35 KB • TXT • Feb 03, 2026 19:43✓' }).getByRole('listitem').click();
  await page.getByRole('listitem').filter({ hasText: 'meeting_saved_closed_caption.txt41.35 KB • TXT • Feb 03, 2026 19:43✓' }).getByRole('listitem').click();
  await page.getByRole('listitem').filter({ hasText: 'meeting_saved_closed_caption.txt41.35 KB • TXT • Feb 03, 2026 19:43✓' }).getByRole('listitem').click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByLabel('Sign Out').getByRole('button', { name: 'Sign Out' }).click();
});await page.getByLabel('Sign Out').getByRole('button', { name: 'Sign Out' }).click();